# Generated by Django 2.2.3 on 2019-07-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='silka',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
